services:
  - type: web
    name: followupmate-backend
    env: node
    buildCommand: npm install && npm run build:server
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: development
